name: Deploy to Web server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js & build
      run: npm install && npm run build

    - name: Build HTML
      uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_dir: md
        output_dir: ./dist/
        build_html: true
        build_pdf: false
        table_of_contents: false

    - name: Generate the sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        path-to-root: ./dist
        base-url-path: https://altmagick.com/

    - name: Uploading to the Web server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        local-dir: ./dist/
        server-dir: ${{ secrets.ftp_dir }}
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}